server:
  port: APP_PORT
  swaggerSchema: SWAGGER_SCHEMA
  hostname: SERVER_HOSTNAME

db:
  postgres:
    host: MAIN_POSTGRES_HOST
    port: MAIN_POSTGRES_PORT
    username: MAIN_POSTGRES_USER
    password: MAIN_POSTGRES_PASSWORD
    database: MAIN_POSTGRES_DB
    ssl:
      __name: MAIN_POSTGRES_SSL
      __format: json
    schema: MAIN_POSTGRES_SCHEMA
    synchronize:
      __name: MAIN_POSTGRES_SYNC_ENABLED
      __format: json
    logging:
      __name: MAIN_POSTGRES_LOGGING_ENABLED
      __format: json

youtube:
  apiKey: YOUTUBE_API_KEY

nodemailer:
  host: NODEMAILER_HOST
  port: NODEMAILER_PORT
  secure:
    __name: NODEMAILER_SERCURE
    __format: json
  auth:
    user: NODEMAILER_AUTH_USER
    pass: NODEMAILER_AUTH_PASS
  from: NODEMAILER_FROM
