service:
  name: ShareTube Backend Service
  description: Sharetube backend service
  baseUrl: /api/sharetube
  apiVersion: 0.1.0
  docsBaseUrl: /sharetube/docs

server:
  port: 3001
  swaggerSchema: http
  hostname: localhost:3001
  cors:
    allowedHeaders: 'authorization,content-type'
    exposedHeaders: 'authorization,x-pagination-page,x-pagination-page-size,x-pagination-total'

db:
  postgres:
    type: postgres
    url: postgres://sharetube:sharetube@localhost:5432/sharetube
    dbName: sharetube
    schema: public
    keepConnectionAlive: false
    synchronize: false
    ssl: false
    dropSchema: false
    logging: false
  migration:
    host: localhost
    port: 5432
    database: sharetube
    username: sharetube
    password: sharetube

bcrypt:
  saltRoundQuantity: 14

jsonwebtoken:
  secretKey: sample-jsonwebtoken-secret-key
  expiresIn:  900 # 15 mins
  subject: sharetube-application
  audience: sharetube-user

youtube:
  baseUrl: https://www.googleapis.com/youtube/v3/
  apiKey: sample-secret-key
